name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保有写入权限
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install terser --no-save

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true # 清理旧文件
          token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token 